postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    username: "bn_keycloak"
    database: "db_keycloak"
    existingSecret: keycloak-db-secret
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password